package com.psmsf.lujanapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PeregrinosAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeregrinosAllPropertiesEquals(Peregrinos expected, Peregrinos actual) {
        assertPeregrinosAutoGeneratedPropertiesEquals(expected, actual);
        assertPeregrinosAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeregrinosAllUpdatablePropertiesEquals(Peregrinos expected, Peregrinos actual) {
        assertPeregrinosUpdatableFieldsEquals(expected, actual);
        assertPeregrinosUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeregrinosAutoGeneratedPropertiesEquals(Peregrinos expected, Peregrinos actual) {
        assertThat(actual)
            .as("Verify Peregrinos auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeregrinosUpdatableFieldsEquals(Peregrinos expected, Peregrinos actual) {
        assertThat(actual)
            .as("Verify Peregrinos relevant properties")
            .satisfies(a -> assertThat(a.getNumeroEspecial()).as("check numeroEspecial").isEqualTo(expected.getNumeroEspecial()))
            .satisfies(a -> assertThat(a.getApellido()).as("check apellido").isEqualTo(expected.getApellido()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getNumeroDocumento()).as("check numeroDocumento").isEqualTo(expected.getNumeroDocumento()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getMayorMenor()).as("check mayorMenor").isEqualTo(expected.getMayorMenor()))
            .satisfies(a -> assertThat(a.getSalida()).as("check salida").isEqualTo(expected.getSalida()))
            .satisfies(a -> assertThat(a.getPago()).as("check pago").isEqualTo(expected.getPago()))
            .satisfies(a -> assertThat(a.getFormaPago()).as("check formaPago").isEqualTo(expected.getFormaPago()))
            .satisfies(a -> assertThat(a.getAclaraciones()).as("check aclaraciones").isEqualTo(expected.getAclaraciones()))
            .satisfies(a -> assertThat(a.getCompletoFormulario()).as("check completoFormulario").isEqualTo(expected.getCompletoFormulario())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeregrinosUpdatableRelationshipsEquals(Peregrinos expected, Peregrinos actual) {
        // empty method
    }
}
